```yaml
version: '3.8'

services:
  web:
    image: python:3.9
    container_name: web_service
    command: bash -c "pip install -r requirements.txt && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "8000:8000"
    depends_on:
      - db
  
  db:
    image: sqlite3
    container_name: db_service
    volumes:
      - ./db.sqlite3:/data/db.sqlite3

volumes:
  db_data:
```