version: '3'

services:
  web:
    build: .
    command: gunicorn myproject.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    expose:
      - 8000
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
