```yaml
version: '3.8'

services:
  web:
    image: python:3.9
    container_name: web
    command: bash -c "pip install -r requirements.txt && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=hello_project.settings
    networks:
      - app-network

  db:
    image: sqlite
    container_name: db
    volumes:
      - db_data:/app/hello_project/db
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
```